services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: .env
    healthcheck:
      test: mariadb -e "SELECT 1;"
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
      start_interval: 5s
    volumes:
      - maria_volume:/var/lib/mysql
    restart: always
    networks:
      - inc-net

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: pgrep php-fpm7.4
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s
      start_interval: 5s
    volumes:
      - wp_volume:/usr/share/wordpress
    restart: always
    networks:
      - inc-net

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wp_volume:/usr/share/wordpress
    restart: always
    networks:
      - inc-net

volumes:
  maria_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mde-arpe/data/maria
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/mde-arpe/data/wp

networks:
  inc-net:
