services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file: .env
    # networks:
    #   - inc-maria
  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file: .env
    # networks:
    #   - inc-maria
    #   - inc-nginx
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    env_file: .env
    # networks:
    #   - inc-nginx
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - $PWD/srcs/requirements/nginx/conf:/conf

#maybe it should be only one network
# networks:
#   inc-maria:
#   inc-nginx:
    
  
